name: avamovies
description: Movies Club para personas que le gusta el entretenimeinto.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sotaui:
    git:
      url: https://github.com/hazhi123/sota_ui.git

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/lottie/
